In [53]:
using LowLevelFEM, LinearAlgebra, SparseArrays

In [54]:
openGeometry("beam-1.geo")
#openPreProcessor()

mat = Material("beam")
Pu = Problem([mat], type=:VectorField, dim=2, field=:u, rhs_field=:f)
Pφ = Problem([mat], type=:ScalarField, dim=2, field=:φ, rhs_field=:m, reducedOrder=true)

Info    : Clearing all models and views...
Info    : Done clearing all models and views
Info    : Reading 'beam-1.geo'...
Info    : Meshing 1D...
Info    : [  0%] Meshing curve 1 (Line)
Info    : [ 60%] Meshing curve 2 (Line)
Info    : Done meshing 1D (Wall 0.000518673s, CPU 0.000304s)
Info    : Meshing order 2 (curvilinear on)...
Info    : [  0%] Meshing curve 1 order 2
Info    : [ 60%] Meshing curve 2 order 2
Info    : Done meshing order 2 (Wall 0.000311043s, CPU 0.000268s)
Info    : 41 nodes 23 elements
Info    : Done reading 'beam-1.geo'


Problem("beam-1", :ScalarField, 2, 1, Material[Material("beam", :Hooke, 200000.0, 0.3, 115384.61538461536, 76923.07692307692, 166666.66666666663, 7.85e-9, 45.0, 4.2e8, 1.2e-5, 1.0e-7, 0.1, 1.0)], 1.0, 41, LowLevelFEM.Geometry("", "", 0, 0, nothing, nothing, nothing, nothing), :φ, :m, true)

In [55]:
a = 80
v = 2
E = mat.E
G = mat.μ
Iz = a^4 / 12 - (a - 2v)^4 / 12
κ = 2 / 3
A = a * a - (a - 2v)^2

624

In [56]:
t = tangentVector(Pu, "beam")
tx, ty, tz = t[1], t[2], t[3]

nx = -ty
ny = tx
nz = 0

0

In [57]:
showElementResults(t)
showElementResults(VectorField([nx, ny, 0ny]))

1

In [58]:
a = [tx * tx tx * ty ty * tx ty * ty]   # axial projector
s = [nx * tx nx * ty ny * tx ny * ty]   # shear projector

1×4 Matrix{ScalarField}:
 ScalarField([[-0.0; -0.0; -0.0;;], [-0.0; -0.0; -0.0;;], [-0.0; -0.0; -0.0;;], [-0.0; -0.0; -0.0;;], [-0.0; -0.0; -0.0;;], [-0.0; -0.0; -0.0;;], [-0.0; -0.0; -0.0;;], [-0.0; -0.0; -0.0;;], [-0.0; -0.0; -0.0;;], [-0.0; -0.0; -0.0;;], [-0.0; -0.0; -0.0;;], [-0.0; -0.0; -0.0;;], [-0.0; -0.0; -0.0;;], [-0.0; -0.0; -0.0;;], [-0.0; -0.0; -0.0;;], [-0.0; -0.0; -0.0;;], [-0.0; -0.0; -0.0;;], [-0.0; -0.0; -0.0;;], [-0.0; -0.0; -0.0;;], [-0.0; -0.0; -0.0;;]], Matrix{Float64}(undef, 0, 0), [0.0], [4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23], 1, :scalar, Problem("beam-1", :VectorField, 2, 2, Material[Material("beam", :Hooke, 200000.0, 0.3, 1.15385e5, 76923.1, 1.66667e5, 7.85e-9, 45.0, 4.2e8, 1.2e-5, 1.0e-7, 0.1, 1.0)], 1.0, 41, Geometry("", "", 0, 0, nothing, nothing, nothing, nothing), :u, :f, false))  …  ScalarField([[0.0; 0.0; 0.0;;], [0.0; 0.0; 0.0;;], [0.0; 0.0; 0.0;;], [0.0; 0.0; 0.0;;], [0.0; 0.0; 0.0;;], [0.0; 0.0; 0.0;;], [0.0; 0.0; 

In [59]:
Cuu = E * A * (a' * a) + κ * G * A * (s' * s)

Cuφ = -κ * G * A * s'   # 4×1
Cφu = -κ * G * A * s    # 1×4

1×4 Matrix{ScalarField}:
 ScalarField([[0.0; 0.0; 0.0;;], [0.0; 0.0; 0.0;;], [0.0; 0.0; 0.0;;], [0.0; 0.0; 0.0;;], [0.0; 0.0; 0.0;;], [0.0; 0.0; 0.0;;], [0.0; 0.0; 0.0;;], [0.0; 0.0; 0.0;;], [0.0; 0.0; 0.0;;], [0.0; 0.0; 0.0;;], [0.0; 0.0; 0.0;;], [0.0; 0.0; 0.0;;], [0.0; 0.0; 0.0;;], [0.0; 0.0; 0.0;;], [0.0; 0.0; 0.0;;], [0.0; 0.0; 0.0;;], [0.0; 0.0; 0.0;;], [0.0; 0.0; 0.0;;], [0.0; 0.0; 0.0;;], [0.0; 0.0; 0.0;;]], Matrix{Float64}(undef, 0, 0), [0.0], [4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23], 1, :scalar, Problem("beam-1", :VectorField, 2, 2, Material[Material("beam", :Hooke, 200000.0, 0.3, 1.15385e5, 76923.1, 1.66667e5, 7.85e-9, 45.0, 4.2e8, 1.2e-5, 1.0e-7, 0.1, 1.0)], 1.0, 41, Geometry("", "", 0, 0, nothing, nothing, nothing, nothing), :u, :f, false))  …  ScalarField([[-0.0; -0.0; -0.0;;], [-0.0; -0.0; -0.0;;], [-0.0; -0.0; -0.0;;], [-0.0; -0.0; -0.0;;], [-0.0; -0.0; -0.0;;], [-0.0; -0.0; -0.0;;], [-0.0; -0.0; -0.0;;], [-0.0; -0.0; -0.0;;], [-0.0; -0

In [60]:
Kuu = ∫(Grad(Pu) ⋅ Cuu ⋅ Grad(Pu); Γ="beam")

Kuφ = ∫(Grad(Pu) ⋅ Cuφ ⋅ Id(Pφ); Γ="beam")
Kφu = ∫(Id(Pφ) ⋅ Cφu ⋅ Grad(Pu); Γ="beam")

Kφφ = ∫(Id(Pφ) ⋅ (κ * G * A) ⋅ Id(Pφ); Γ="beam") +
      ∫(AxialGrad(Pφ) ⋅ (E * Iz) ⋅ AxialGrad(Pφ); Γ="beam")

sparse([1, 4, 13, 2, 12, 22, 23, 32, 3, 31  …  38, 29, 30, 39, 30, 31, 40, 3, 31, 41], [1, 1, 1, 2, 2, 2, 2, 2, 3, 3  …  38, 39, 39, 39, 40, 40, 40, 41, 41, 41], [3.3813759999999986e9, 3.154346666666662e8, -3.163477333333332e9, 6.762751999999997e9, 3.154346666666662e8, -3.163477333333332e9, 3.154346666666662e8, -3.163477333333332e9, 3.381375999999999e9, 3.154346666666662e8  …  8.460287999999989e9, -3.163477333333332e9, -3.163477333333332e9, 8.460287999999997e9, -3.163477333333332e9, -3.163477333333332e9, 8.460287999999997e9, -3.163477333333332e9, -3.163477333333332e9, 8.460287999999997e9], 41, 41)

In [61]:
K = SystemMatrix([Kuu Kuφ; Kφu Kφφ])

sparse([1, 7, 25, 2, 8, 26, 83, 86, 95, 3  …  59, 61, 112, 113, 122, 5, 61, 85, 113, 123], [1, 1, 1, 2, 2, 2, 2, 2, 2, 3  …  122, 122, 122, 122, 122, 123, 123, 123, 123, 123], [2.9119999999999986e6, 415999.99999999953, -3.3279999999999986e6, 746666.6666666664, 106666.66666666657, -853333.333333333, 1.5999999999999993e7, -5.33333333333333e6, 2.133333333333333e7, 3.6586666666666656e6  …  -2.133333333333333e7, 2.133333333333333e7, -3.163477333333332e9, -3.163477333333332e9, 8.460287999999997e9, 2.133333333333333e7, -2.133333333333333e7, -3.163477333333332e9, -3.163477333333332e9, 8.460287999999997e9], 123, 123)

In [62]:
supp_u = BoundaryCondition("A", problem=Pu, ux=0, uy=0)
supp_φ = BoundaryCondition("A", problem=Pφ, φ=0)

BoundaryCondition("A", Problem("beam-1", :ScalarField, 2, 1, Material[Material("beam", :Hooke, 200000.0, 0.3, 115384.61538461536, 76923.07692307692, 166666.66666666663, 7.85e-9, 45.0, 4.2e8, 1.2e-5, 1.0e-7, 0.1, 1.0)], 1.0, 41, LowLevelFEM.Geometry("", "", 0, 0, nothing, nothing, nothing, nothing), :φ, :m, true), Dict{Symbol, Union{Function, Number, ScalarField}}(:φ => 0))

In [63]:
fu = ∫(Pu ⋅ [1, 0], Γ="C")
fφ = ∫(Pφ ⋅ 0, Γ="B")
fu2 = ∫(Pu ⋅ [0.0, -0.0], Γ="beam")

nodal VectorField
[0.0; 0.0; … ; 0.0; 0.0;;]

In [64]:
F = SystemVector([fu + fu2, fφ])

SystemVector([0.0; 0.0; … ; 0.0; 0.0;;], nothing, Problem[Problem("beam-1", :VectorField, 2, 2, Material[Material("beam", :Hooke, 200000.0, 0.3, 115384.61538461536, 76923.07692307692, 166666.66666666663, 7.85e-9, 45.0, 4.2e8, 1.2e-5, 1.0e-7, 0.1, 1.0)], 1.0, 41, LowLevelFEM.Geometry("", "", 0, 0, nothing, nothing, nothing, nothing), :u, :f, false), Problem("beam-1", :ScalarField, 2, 1, Material[Material("beam", :Hooke, 200000.0, 0.3, 115384.61538461536, 76923.07692307692, 166666.66666666663, 7.85e-9, 45.0, 4.2e8, 1.2e-5, 1.0e-7, 0.1, 1.0)], 1.0, 41, LowLevelFEM.Geometry("", "", 0, 0, nothing, nothing, nothing, nothing), :φ, :m, true)], [0, 82])

In [65]:


Tφ, Rφ = reductionMatrices(Pφ)

Tu = spdiagm(0 => ones(Pu.non*Pu.pdim))
TT = blockdiag(Tu, Tφ)

Kr = TT' * K.A * TT

eigvals(Matrix(Kr))

103-element Vector{ComplexF64}:
  -2.23571325120772e-8 + 0.0im
 2.3404695183932863e-8 - 2.4822554899897842e-8im
 2.3404695183932863e-8 + 2.4822554899897842e-8im
    100.89128283881378 + 0.0im
    1471.6385220992208 + 0.0im
     2903.744425473324 + 0.0im
    12824.443518337464 + 0.0im
     17510.11162682239 + 0.0im
     42582.89067626579 + 0.0im
     43414.18734723355 + 0.0im
     60787.77504513001 + 0.0im
      70777.0902241116 + 0.0im
    122998.55555959136 + 0.0im
                       ⋮
  4.2578704313741965e9 + 0.0im
   4.482390720860466e9 + 0.0im
   4.710370884827574e9 + 0.0im
   4.936553767922351e9 + 0.0im
   5.155549561795238e9 + 0.0im
   5.362403901775834e9 + 0.0im
   5.552276620563673e9 + 0.0im
   5.720915431290006e9 + 0.0im
   5.864404766691359e9 + 0.0im
   5.979556569796184e9 + 0.0im
   6.063694666860485e9 + 0.0im
   6.114975669376318e9 + 0.0im

In [66]:
Tφ, Rφ = reductionMatrices(Pφ)

norm(Rφ * Tφ - I, Inf)


0.0

In [67]:
size(Tφ)

(41, 21)

In [68]:
ndofs(P::Problem) = P.non * P.pdim

ndofs (generic function with 1 method)

In [69]:
Tφ, Rφ = reductionMatrices(Pφ)

Tu = spdiagm(0 => ones(ndofs(Pu)))
Ru = Tu

T = blockdiag(Tu, Tφ)
R = blockdiag(Ru, Rφ)

fixed = constrainedDoFs(K, [supp_u, supp_φ])
free = freeDoFs(K, [supp_u, supp_φ])
xD = zeros(size(R, 2))

free_r, fixed_r, xD_r =
    reduced_bc_data(R, fixed, xD[:, 1])

Kr = T' * K.A * T

λ = eigvals(Symmetric(Matrix(Kr[free_r, free_r])))
λ[1:10]

10-element Vector{Float64}:
     8.242665602809387
    59.164308828724664
  1364.9409193589063
  2737.330253118658
 10125.091805195758
 14172.027419297618
 20640.39106678701
 42700.92438783577
 52749.11537410075
 67011.37091376414

In [70]:
λ = eigvals(Symmetric(Matrix(Kr[free_r, free_r])))

λmax = maximum(abs, λ)
tol = 1e-12 * λmax

count(abs.(λ) .< tol)

0

In [71]:
#u, v, φ = solveField(K, F, support=[supp_u, supp_v, supp_φ, supp_u0, supp_v0, supp_φ0])
u, φ = solveField(K, F, support=[supp_u, supp_φ])

(VectorField(Matrix{Float64}[], [0.0; 0.0; … ; 0.009968668713518132; -0.003948498938580149;;], [0.0], Int64[], 1, :v2D, Problem("beam-1", :VectorField, 2, 2, Material[Material("beam", :Hooke, 200000.0, 0.3, 115384.61538461536, 76923.07692307692, 166666.66666666663, 7.85e-9, 45.0, 4.2e8, 1.2e-5, 1.0e-7, 0.1, 1.0)], 1.0, 41, LowLevelFEM.Geometry("", "", 0, 0, nothing, nothing, nothing, nothing), :u, :f, false)), ScalarField(Matrix{Float64}[], [0.0; -7.896997877212314e-6; … ; -1.1746784342419573e-5; -1.1825754321192609e-5;;], [0.0], Int64[], 1, :scalar, Problem("beam-1", :ScalarField, 2, 1, Material[Material("beam", :Hooke, 200000.0, 0.3, 115384.61538461536, 76923.07692307692, 166666.66666666663, 7.85e-9, 45.0, 4.2e8, 1.2e-5, 1.0e-7, 0.1, 1.0)], 1.0, 41, LowLevelFEM.Geometry("", "", 0, 0, nothing, nothing, nothing, nothing), :φ, :m, true)))

In [72]:
showDoFResults(fu, name="force")
u0 = showDoFResults(u, name="u", factor=1, visible=true)
φ0 = showDoFResults(φ, name="φ")

4

In [73]:
n = VectorField([nx, ny, 0nx])

elementwise VectorField
[[-0.0; 1.0; … ; 1.0; -0.0;;], [-0.0; 1.0; … ; 1.0; -0.0;;], [-0.0; 1.0; … ; 1.0; -0.0;;], [-0.0; 1.0; … ; 1.0; -0.0;;], [-0.0; 1.0; … ; 1.0; -0.0;;], [-0.0; 1.0; … ; 1.0; -0.0;;], [-0.0; 1.0; … ; 1.0; -0.0;;], [-0.0; 1.0; … ; 1.0; -0.0;;], [-0.0; 1.0; … ; 1.0; -0.0;;], [-0.0; 1.0; … ; 1.0; -0.0;;], [-1.0; 0.0; … ; 0.0; -0.0;;], [-1.0; 0.0; … ; 0.0; -0.0;;], [-1.0; 0.0; … ; 0.0; -0.0;;], [-1.0; 0.0; … ; 0.0; -0.0;;], [-1.0; 0.0; … ; 0.0; -0.0;;], [-1.0; 0.0; … ; 0.0; -0.0;;], [-1.0; 0.0; … ; 0.0; -0.0;;], [-1.0; 0.0; … ; 0.0; -0.0;;], [-1.0; 0.0; … ; 0.0; -0.0;;], [-1.0; 0.0; … ; 0.0; -0.0;;]]

In [74]:
g = grad(expandTo3D(u))

ε = t ⋅ (g * t)
γ = n ⋅ (g * t) - nodesToElements(φ)

κb = grad(φ) ⋅ t

N = E * A * ε
T = κ * G * A * γ
Mh = E * Iz * κb

elementwise ScalarField
[[-999.999999973637; -999.9999999736369; -999.999999973637;;], [-999.9999999773545; -999.9999999773537; -999.9999999773535;;], [-999.9999999810726; -999.9999999810709; -999.9999999810722;;], [-999.9999999847983; -999.9999999847983; -999.999999984799;;], [-999.9999999885473; -999.9999999885406; -999.9999999885431;;], [-999.9999999923215; -999.9999999923249; -999.9999999923232;;], [-999.999999996146; -999.9999999961426; -999.9999999961426;;], [-999.9999999999771; -999.9999999999839; -999.9999999999789;;], [-1000.0000000038352; -1000.0000000038352; -1000.0000000038352;;], [-1000.000000007777; -1000.000000007777; -1000.000000007777;;], [-950.0000000090611; -950.0000000090611; -950.0000000090628;;], [-850.0000000076137; -850.0000000076137; -850.000000007612;;], [-750.00000000624; -750.0000000062266; -750.0000000062333;;], [-650.0000000049602; -650.0000000049467; -650.0000000049534;;], [-550.0000000038077; -550.000000003801; -550.0000000038044;;], [-450.0000000028363;

In [75]:
N0 = showElementResults(N, name="N")
T0 = showElementResults(T, name="T")
Mh0 = showElementResults(Mh, name="Mh")

7

In [76]:
plotOnPath("beam", N0)
plotOnPath("beam", T0)
plotOnPath("beam", Mh0)

10

In [77]:
openPostProcessor()

-------------------------------------------------------
Version       : 4.15.2-git
License       : GNU General Public License
Build OS      : Linux64-sdk
Build date    : 19700101
Build host    : amdci7.julia.csail.mit.edu
Build options : 64Bit ALGLIB[contrib] ANN[contrib] Bamg Blossom Cairo DIntegration Dlopen DomHex Eigen[contrib] Fltk GMP Gmm[contrib] Hxt Jpeg Kbipack LinuxJoystick MathEx[contrib] Mesh Metis[contrib] Mmg Mpeg Netgen Nii2mesh ONELAB ONELABMetamodel OpenCASCADE OpenCASCADE-CAF OpenGL OpenMP OptHom Parser Plugins Png Post QuadMeshingTools QuadTri Solver TetGen/BR TinyXML2[contrib] Untangle Voro++[contrib] WinslowUntangler Zlib tinyobjloader
FLTK version  : 1.3.8
OCC version   : 7.9.2
Packaged by   : root
Web site      : https://gmsh.info
Issue tracker : https://gitlab.onelab.info/gmsh/gmsh/issues
-------------------------------------------------------


In [78]:
@show maximum(u[1].a)
@show minimum(u[1].a)

maximum((u[1]).a) = 0.010562012491945097
minimum((u[1]).a) = 0.0


0.0