In [1]:
using LowLevelFEM

In [2]:
gmsh.initialize()
gmsh.open("cube1.geo")

mat = material("cube")
prob = Problem([mat])

Info    : Reading 'cube1.geo'...
Info    : Meshing 1D...
Info    : [  0%] Meshing curve 1 (Line)
Info    : [ 10%] Meshing curve 2 (Line)
Info    : [ 20%] Meshing curve 3 (Line)
Info    : [ 30%] Meshing curve 4 (Line)
Info    : [ 40%] Meshing curve 5 (Line)
Info    : [ 50%] Meshing curve 6 (Line)
Info    : [ 60%] Meshing curve 7 (Line)
Info    : [ 60%] Meshing curve 8 (Line)
Info    : [ 70%] Meshing curve 9 (Line)
Info    : [ 80%] Meshing curve 10 (Line)
Info    : [ 90%] Meshing curve 11 (Line)
Info    : [100%] Meshing curve 12 (Line)
Info    : Done meshing 1D (Wall 0.000708657s, CPU 0.00071s)
Info    : Meshing 2D...
Info    : [  0%] Meshing surface 1 (Transfinite)
Info    : [ 20%] Meshing surface 2 (Transfinite)
Info    : [ 40%] Meshing surface 3 (Transfinite)
Info    : [ 60%] Meshing surface 4 (Transfinite)
Info    : [ 70%] Meshing surface 5 (Transfinite)
Info    : [ 90%] Meshing surface 6 (Transfinite)
Info    : Done meshing 2D (Wall 0.000133439s, CPU 0.000133s)
Info    : Meshing 3D.

Problem("cube1", :Solid, 3, 3, LowLevelFEM.Material[LowLevelFEM.Material("cube", :Hooke, 200000.0, 0.3, 7.85e-9, 45.0, 4.2e8, 1.2e-5, 115384.61538461536, 76923.07692307692, 166666.66666666666, 1.0e-7, 0.1, 1.0)], 1.0, 343, LowLevelFEM.Geometry("", "", 0, 0, nothing, nothing, nothing, nothing))

In [3]:
R00 = tensorField(prob, "cube", [0 0 0; 0 0 0; 0 0 0])
RR = zeros(size(R00.a, 1), 100)

for i in 1:100
    φ = i / 100 * π
    f1(x, y, z) = cos(φ)
    f2(x, y, z) = -sin(φ)
    f3(x, y, z) = sin(φ)
    R0 = [f1 f2 0; f3 f1 0; 0 0 1]
    R1 = tensorField(prob, "cube", R0)
    RR[:, i] = R1.a
end

t = [i for i in 1:100]
R = TensorField([], RR, t, [], 100, :tensor, R00.model)

TensorField

3087×100 Matrix{Float64}:
  0.999507    0.998027    0.995562    0.992115  …  -0.999507   -1.0
  0.0314108   0.0627905   0.0941083   0.125333      0.0314108   1.22465e-16
  0.0         0.0         0.0         0.0           0.0         0.0
 -0.0314108  -0.0627905  -0.0941083  -0.125333     -0.0314108  -1.22465e-16
  0.999507    0.998027    0.995562    0.992115     -0.999507   -1.0
  0.0         0.0         0.0         0.0       …   0.0         0.0
  0.0         0.0         0.0         0.0           0.0         0.0
  0.0         0.0         0.0         0.0           0.0         0.0
  1.0         1.0         1.0         1.0           1.0         1.0
  0.999507    0.998027    0.995562    0.992115     -0.999507   -1.0
  0.0314108   0.0627905   0.0941083   0.125333  …   0.0314108   1.22465e-16
  0.0         0.0         0.0         0.0           0.0         0.0
 -0.0314108  -0.0627905  -0.0941083  -0.125333     -0.0314108  -1.22465e-16
  ⋮                                             ⋱         

In [ ]:
r = nodePositionVector(prob)
r0 = zeros(size(r.a, 1), 100)
for i in 1:100
    r0[:, i] = r.a
end
r = VectorField([], r0, t, [], 100, :v3D, r.model)
r = nodesToElements(r)

VectorField

8-element Vector{Matrix{Float64}}:
 [1.815677238189058e-15 1.815677238189058e-15 … 1.815677238189058e-15 1.815677238189058e-15; 0.5000000000000047 0.5000000000000047 … 0.5000000000000047 0.5000000000000047; … ; 0.3333333333333332 0.3333333333333332 … 0.3333333333333332 0.3333333333333332; 0.16666666666666646 0.16666666666666646 … 0.16666666666666646 0.16666666666666646]
 [0.5000000000000072 0.5000000000000072 … 0.5000000000000072 0.5000000000000072; 0.5000000000000046 0.5000000000000046 … 0.5000000000000046 0.5000000000000046; … ; 0.33333333333333315 0.33333333333333315 … 0.33333333333333315 0.33333333333333315; 0.16666666666666646 0.16666666666666646 … 0.16666666666666646 0.16666666666666646]
 [1.8156772381890574e-15 1.8156772381890574e-15 … 1.8156772381890574e-15 1.8156772381890574e-15; 1.0000000000000084 1.0000000000000084 … 1.0000000000000084 1.0000000000000084; … ; 0.8333333333333323 0.8333333333333323 … 0.8333333333333323 0.8333333333333323; 0.1666666666666665 0.1666666666666665 

In [6]:
R = nodesToElements(R)

TensorField

8-element Vector{Matrix{Float64}}:
 [0.9995065603657415 0.9980267284282813 … -0.9995065603657415 -1.0000000000000093; 0.03141075907812859 0.06279051952931397 … 0.031410759078128535 1.2246467991473643e-16; … ; 0.0 0.0 … 0.0 0.0; 0.9999999999999993 0.9999999999999993 … 0.9999999999999993 0.9999999999999993]
 [0.9995065603657415 0.9980267284282813 … -0.9995065603657415 -1.0000000000000093; 0.03141075907812859 0.06279051952931397 … 0.031410759078128535 1.2246467991473643e-16; … ; 0.0 0.0 … 0.0 0.0; 0.9999999999999993 0.9999999999999993 … 0.9999999999999993 0.9999999999999993]
 [0.9995065603657415 0.9980267284282813 … -0.9995065603657415 -1.0000000000000093; 0.03141075907812859 0.06279051952931397 … 0.031410759078128535 1.2246467991473643e-16; … ; 0.0 0.0 … 0.0 0.0; 0.9999999999999993 0.9999999999999993 … 0.9999999999999993 0.9999999999999993]
 [0.9995065603657415 0.9980267284282813 … -0.9995065603657415 -1.0000000000000093; 0.03141075907812859 0.06279051952931397 … 0.031410759078128535 1.2

In [ ]:
showDeformationResults(R * r)

2

In [9]:
openPostProcessor()

-------------------------------------------------------
Version       : 4.13.1
License       : GNU General Public License
Build OS      : Linux64-sdk
Build date    : 19700101
Build host    : amdci7.julia.csail.mit.edu
Build options : 64Bit ALGLIB[contrib] ANN[contrib] Bamg Blossom Cairo DIntegration Dlopen DomHex Eigen[contrib] Fltk GMP Gmm[contrib] Hxt Jpeg Kbipack LinuxJoystick MathEx[contrib] Mesh Metis[contrib] Mmg Mpeg Netgen Nii2mesh ONELAB ONELABMetamodel OpenCASCADE OpenCASCADE-CAF OpenGL OpenMP OptHom Parser Plugins Png Post QuadMeshingTools QuadTri Solver TetGen/BR TinyXML2[contrib] Untangle Voro++[contrib] WinslowUntangler Zlib
FLTK version  : 1.3.8
OCC version   : 7.7.2
Packaged by   : root
Web site      : https://gmsh.info
Issue tracker : https://gitlab.onelab.info/gmsh/gmsh/issues
-------------------------------------------------------


XOpenIM() failed
XRequest.18: BadValue 0x0
Fontconfig warning: using without calling FcInit()
