In [1]:
using LowLevelFEM

[ Info: Precompiling LowLevelFEM [6171b9fb-adbf-4751-adb9-5faded75de07] (cache misses: include_dependency fsize change (2), wrong dep version loaded (2), incompatible header (14))

SYSTEM: caught exception of type :MethodError while trying to print a failed Task notice; giving up

SYSTEM: caught exception of type :MethodError while trying to print a failed Task notice; giving up

SYSTEM: caught exception of type :MethodError while trying to print a failed Task notice; giving up

SYSTEM: caught exception of type :MethodError while trying to print a failed Task notice; giving up

SYSTEM: caught exception of type :MethodError while trying to print a failed Task notice; giving up


In [2]:
gmsh.initialize()
gmsh.open("cube1.geo")

mat = Material("cube")
prob_v = Problem([mat], type=:VectorField)
prob_p = Problem([mat], type=:ScalarField)

Info    : Reading 'cube1.geo'...
Info    : Meshing 1D...
Info    : [  0%] Meshing curve 1 (Line)
Info    : [ 10%] Meshing curve 2 (Line)
Info    : [ 20%] Meshing curve 3 (Line)
Info    : [ 30%] Meshing curve 4 (Line)
Info    : [ 40%] Meshing curve 5 (Line)
Info    : [ 50%] Meshing curve 6 (Line)
Info    : [ 60%] Meshing curve 7 (Line)
Info    : [ 60%] Meshing curve 8 (Line)
Info    : [ 70%] Meshing curve 9 (Line)
Info    : [ 80%] Meshing curve 10 (Line)
Info    : [ 90%] Meshing curve 11 (Line)
Info    : [100%] Meshing curve 12 (Line)
Info    : Done meshing 1D (Wall 0.000623591s, CPU 0.000578s)
Info    : Meshing 2D...
Info    : [  0%] Meshing surface 1 (Transfinite)
Info    : [ 20%] Meshing surface 2 (Transfinite)
Info    : [ 40%] Meshing surface 3 (Transfinite)
Info    : [ 60%] Meshing surface 4 (Transfinite)
Info    : [ 70%] Meshing surface 5 (Transfinite)
Info    : [ 90%] Meshing surface 6 (Transfinite)
Info    : Done meshing 2D (Wall 0.000275872s, CPU 0s)
Info    : Meshing 3D...
Inf

Problem("cube1", :ScalarField, 3, 1, Material[Material("cube", :Hooke, 200000.0, 0.3, 115384.61538461536, 76923.07692307692, 166666.66666666663, 7.85e-9, 45.0, 4.2e8, 1.2e-5, 1.0e-7, 0.1, 1.0)], 1.0, 6859, LowLevelFEM.Geometry("", "", 0, 0, nothing, nothing, nothing, nothing))

In [3]:
G = gradMatrix(prob_v, prob_p)

sparse([1, 2, 3, 46, 47, 48, 73, 74, 75, 76  …  20511, 20521, 20522, 20523, 20569, 20570, 20571, 20575, 20576, 20577], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1  …  6859, 6859, 6859, 6859, 6859, 6859, 6859, 6859, 6859, 6859], [0.00010973936899862796, 0.00010973936899862812, -0.00010973936899862811, -2.7434842249657125e-5, -2.7434842249657037e-5, -3.657978966620935e-5, 5.4869684499314366e-5, 5.4869684499314014e-5, 0.00014631915866483743, -2.7434842249656942e-5  …  2.1599340154984659e-19, 2.0328790734103208e-19, 0.002341106538637403, 5.082197683525802e-21, 0.002341106538637403, 1.0058516248644817e-19, 1.3361944742936588e-19, -7.877406409464993e-19, -3.3034284942917713e-19, 1.2536087619363645e-19], 20577, 6859)

In [4]:
G.A

20577×6859 SparseArrays.SparseMatrixCSC{Float64, Int64} with 1164350 stored entries:
⎡⣿⣿⣿⣿⣿⣿⣷⣗⣺⣸⣒⠇⠇⠾⢸⢿⣿⎤
⎢⣿⡇⣿⡟⣛⢿⡟⠛⠛⠿⠿⠿⣭⣭⣭⣉⣉⎥
⎢⣿⢿⣿⣿⣛⢯⡛⠛⠿⠿⠿⣭⣭⣭⣉⣉⣉⎥
⎢⢻⠛⣿⢹⣿⣿⡇⣟⢸⢸⡂⡇⡇⢸⢹⠉⡏⎥
⎢⢿⠟⢻⣿⣿⣿⡇⡏⣿⢸⢹⡇⡇⣿⢸⢸⣿⎥
⎢⣿⣿⠿⢿⣿⡏⣷⡇⠈⠈⠈⠁⠁⠉⠘⠘⠛⎥
⎢⣿⣿⡾⠿⣷⠃⡎⠃⠀⠀⠀⠀⠀⠀⢰⣶⡶⎥
⎢⣿⣿⣷⣶⢿⡆⣷⣶⣤⣄⡀⠀⠀⠀⠀⠙⠛⎥
⎢⣿⣿⣿⣿⠀⢿⡀⠈⠙⠛⠿⢿⣶⣦⣄⣀⠀⎥
⎢⣿⣿⠿⢻⢻⡞⣧⢶⠀⠀⠀⠀⠈⠉⠛⠛⠛⎥
⎢⣿⣿⢀⣸⡟⡇⢹⡾⣇⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⢿⣿⠾⠛⢳⡇⣦⢷⣹⡄⠀⠀⠀⠀⠀⠀⠀⎥
⎢⣸⣿⢀⡀⠘⡇⢹⡞⣯⣷⠀⠀⠀⠀⠀⠀⠀⎥
⎢⢻⣿⠛⠉⠀⡇⠀⢿⣹⡼⣇⠀⠀⠀⠀⠀⠀⎥
⎢⣸⣿⢀⣀⠀⣿⠀⠘⣯⣷⢻⡄⠀⠀⠀⠀⠀⎥
⎢⢻⣿⠛⠉⠀⣿⠀⠀⢹⡾⣏⣧⠀⠀⠀⠀⠀⎥
⎢⣼⣿⢠⣄⠀⣿⠀⠀⠀⢷⢻⣼⡆⠀⠀⠀⠀⎥
⎢⢻⣿⠛⠉⠀⣿⠀⠀⠀⠸⣏⣷⢿⡀⠀⠀⠀⎥
⎢⣼⣿⢠⣄⠀⢿⠀⠀⠀⠀⢻⡼⡟⣧⠀⠀⠀⎥
⎢⢹⣿⡏⠉⠀⢸⠀⠀⠀⠀⠀⣷⢿⣸⡆⠀⠀⎥
⎢⣼⣿⣧⣄⠀⢸⡆⠀⠀⠀⠀⠸⣟⣧⢿⡀⠀⎥
⎢⢹⣿⡏⠀⠀⢸⡇⠀⠀⠀⠀⠀⢻⣼⡞⣇⠀⎥
⎢⣼⣿⣧⣤⡀⢸⡇⠀⠀⠀⠀⠀⠈⣧⢿⣹⡄⎥
⎢⣿⣿⡏⠀⣿⢸⡇⠀⠀⠀⠀⠀⠀⠸⡞⣧⣇⎥
⎢⣿⣿⣷⣦⣿⠸⡇⠀⠀⠀⠀⠀⠀⠀⢿⣹⣿⎥
⎣⣿⣿⣧⣄⣿⠀⡇⠀⠀⠀⠀⠀⠀⠀⠈⢿⣷⎦

In [5]:
u = vectorField(prob_v, "cube", [1, 2, 3])

VectorField
[1.0; 2.0; … ; 2.0; 3.0;;]

In [6]:
C = navierStokesAdvectionMatrix(prob_v, u)

sparse([1, 46, 73, 76, 100, 484, 508, 805, 1375, 1453  …  5832, 5838, 7374, 19599, 19695, 19707, 20511, 20523, 20571, 20577], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1  …  20577, 20577, 20577, 20577, 20577, 20577, 20577, 20577, 20577, 20577], [9.96388678656875e-20, -2.7434842249657227e-5, 0.0002743484224965697, 1.8289894833104496e-5, -0.0001828989483310471, 9.144947416552445e-6, -9.144947416552288e-5, 2.286236854138166e-6, 3.2007315957933204e-5, -5.944215820759022e-5  …  -0.0005852766346593491, -0.007023319615912203, 0.00021947873799725375, 0.0014631915866483772, 0.0011705532693187, 0.007023319615912206, 0.0008779149519890266, 0.004682213077274803, 0.0023411065386374024, 2.439454888092385e-18], 20577, 20577)

In [7]:
C.A

20577×20577 SparseArrays.SparseMatrixCSC{Float64, Int64} with 1166184 stored entries:
⎡⣿⣿⣿⡿⢺⡧⣿⠼⣿⣾⣟⣿⣟⣛⣿⣶⣾⣷⣤⣜⣓⣀⣘⣓⣀⣐⣓⣀⣐⣓⣀⣐⣓⣀⣐⣟⣛⣻⣟⣿⎤
⎢⣿⡿⠻⣦⣼⡇⣿⢠⣤⣴⡶⣯⣽⣷⣯⣭⣭⣭⣭⣭⣭⣭⣭⣽⣿⣿⣿⡿⠿⠿⠷⠶⠶⠶⢶⡶⠶⣶⡶⣦⎥
⎢⠾⡶⠶⠿⢿⣷⡟⠘⣷⢰⡖⣶⣿⣿⣷⠀⠀⣶⠀⠀⣾⠉⠉⣿⠉⠉⣯⠉⠉⡯⠙⠛⡿⠛⠛⡟⠛⠓⡖⠒⎥
⎢⣛⡟⠛⣛⣛⠉⢿⣷⡏⢸⡇⣿⣿⣿⡏⠀⢸⡏⠀⢸⡏⠀⢸⡏⠀⢸⡏⠀⢸⡏⠀⢸⡏⠀⢸⡇⠀⢸⡇⢶⎥
⎢⣻⣿⢀⣿⢙⣛⣋⣉⡿⣯⣁⢻⠉⠉⡛⠿⣭⡅⠀⠀⠁⠀⠀⠁⠀⠈⠁⠀⠈⠁⠀⠈⠁⠀⠈⣁⣀⡈⣁⡈⎥
⎢⣿⣽⡼⣯⢸⣭⣭⣭⣥⣘⠿⣧⡀⠀⣧⣄⣀⣤⣄⣀⣀⣀⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠙⠻⠯⠿⠯⎥
⎢⣿⢹⢷⣿⣿⣿⣿⣿⡇⠀⠀⠈⠻⣦⡀⠉⠉⠉⠉⠛⠛⠛⠛⠿⠿⠿⠶⣶⣶⣶⣦⣤⣤⣤⣄⣀⣀⣀⠀⠀⎥
⎢⢻⣿⡏⣿⠙⠛⠋⠉⣿⡌⠉⢿⡄⠈⠻⣦⡀⠻⣦⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠉⠉⠉⠉⠉⠉⠉⠉⠉⎥
⎢⢾⣿⡇⣿⢠⣤⡶⠶⠇⠿⠀⣼⡇⠀⣤⡈⠻⣦⡈⠻⣦⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⣀⢿⡇⣿⠀⠀⣀⣀⠀⠀⠀⢹⣧⠀⠈⠻⣦⡈⠻⣦⡈⠻⣦⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠙⢸⡇⣿⡞⠛⠋⠉⠁⠀⠀⢸⣿⠀⠀⠀⠈⠻⣦⡈⠻⣦⡈⠻⣦⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⢶⢸⣇⣿⣧⣤⡶⠶⠄⠀⠀⠈⣿⡄⠀⠀⠀⠀⠈⠻⣦⡈⠻⣦⡈⠻⣦⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⢀⢸⣿⣿⡇⠀⣀⣀⡀⠀⠀⠀⣿⡇⠀⠀⠀⠀⠀⠀⠈⠻⣦⡈⠻⣦⡈⠻⣦⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠙⢸⣿⡿⡏⠛⠋⠉⠁⠀⠀⠀⢸⣧⠀⠀⠀⠀⠀⠀⠀⠀⠈⠻⣦⡈⠻⣦⡈⠻⣦⡀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⢴⢸⣿⡇⡧⡤⡶⠶⠆⠀⠀⠀⢸⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠻⣦⡈⠻⣦⡈⠻⣦⡀⠀⠀⠀⠀⠀⠀⎥
⎢⢀⢸⢹⡇⣷⠀⣀⣀⡀⠀⠀⠀⠈⣿⡄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠻⣦⡈⠻⣦⡈⠻⣦⡀⠀⠀⠀⠀⎥
⎢⠙⢸⢸⡇⣿⠋⠋⠉⠁⠀⠀⠀⠀⣿⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠻⣦⡈⠻⣦⡈⠻⣦⡀⠀⠀⎥
⎢⣴⢼⢸⡷⣿⠤⠶⠶⠆⢠⣄⠀⠀⢹⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠻⣦⡈⠻⣦⡈⠻⣦⠀⎥
⎢⣿⣸⢸⣧⢿⠀⣀⣀⡀⠸⡿⡆⠀⢸⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠻⣦⡈⠻⣦⡹⣧⎥
⎣⣿⣽⠸⣯⢸⠉⢩⣍⡁⠸⡿⡇⠀⠀⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠛⠷⣮⡻⣮⎦

In [8]:
r = C.A * u.a[:, 1]

20577-element Vector{Float64}:
  5.463362509790237e-20
  1.0926725019580474e-19
  3.942938369468768e-19
  0.0
  0.0
  2.168404344971009e-19
  0.0
  0.0
 -1.0842021724855044e-19
  4.0657581468206416e-20
  8.131516293641283e-20
  2.710505431213761e-19
  6.776263578034403e-20
  ⋮
  1.5043305143236374e-18
  3.0086610286472748e-18
 -6.762711050878334e-18
  8.673617379884035e-19
  1.734723475976807e-18
 -8.673617379884035e-19
  4.851804721872632e-18
  9.703609443745265e-18
  1.7157499379583108e-17
 -5.963111948670274e-19
 -1.1926223897340549e-18
  3.7947076036992655e-19

In [9]:
K = symmetricGradientMatrix(prob_v; coefficient=mat.η)

sparse([1, 2, 3, 46, 47, 48, 73, 74, 75, 76  …  20511, 20521, 20522, 20523, 20569, 20570, 20571, 20575, 20576, 20577], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1  …  20577, 20577, 20577, 20577, 20577, 20577, 20577, 20577, 20577, 20577], [1.84362139917695e-9, 3.703703703703695e-10, -3.703703703703698e-10, -2.7983539094650175e-10, -9.259259259259261e-11, 1.2345679012345743e-10, 1.6460905349794694e-10, 1.851851851851868e-10, -4.93827160493828e-10, -2.79835390946501e-10  …  -1.580246913580241e-9, -6.85008944770476e-25, -1.58973773975035e-24, -2.1069958847736292e-9, -4.420246398330242e-24, -3.554291694563791e-25, -2.1069958847736433e-9, -5.816113682013476e-25, 4.006656092053728e-25, 6.742386831275709e-8], 20577, 20577)

In [10]:
G = gradMatrix(prob_v, prob_p)
D = -G'

sparse([1, 16, 25, 26, 34, 162, 170, 269, 459, 485  …  1944, 1946, 2458, 6533, 6565, 6569, 6837, 6841, 6857, 6859], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1  …  20577, 20577, 20577, 20577, 20577, 20577, 20577, 20577, 20577, 20577], [-0.00010973936899862796, 2.743484224965692e-5, -5.4869684499314407e-5, 2.743484224965695e-5, -5.486968449931395e-5, 3.6579789666209534e-5, -0.00014631915866483676, -6.858710562414212e-6, 1.3717421124828458e-5, 1.371742112482858e-5  …  -0.00029263831732967514, -0.0023411065386374015, 3.657978966620879e-5, 0.0002926383173296745, 0.00029263831732967503, 0.0023411065386374007, 1.164670302474663e-19, -2.896852679609707e-19, 8.470329472543003e-20, -1.2536087619363645e-19], 6859, 20577)

In [11]:
f_u = vectorField(prob_v, "cube", [1, 0, 0])
f_p = zeros(prob_p.non)   # inkompresszibilitás

6859-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 ⋮
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

In [12]:
using SparseArrays

function stokesMatrix(K::LowLevelFEM.SystemMatrix, G::LowLevelFEM.SystemMatrix, prob_v::Problem, prob_p::Problem)

    nu = prob_v.dim * prob_v.non
    np = prob_p.non

    Zpp = spzeros(np, np)

    A = [
        K.A G.A;
        -G.A' Zpp
    ]

    return A
end

stokesMatrix (generic function with 1 method)

In [13]:
function stokesRHS(f_u::VectorField, prob_v::Problem, prob_p::Problem)
    fu = f_u.a[:, 1]
    fp = zeros(prob_p.non)
    return vcat(fu, fp)
end



stokesRHS (generic function with 1 method)

In [14]:
K = symmetricGradientMatrix(prob_v)
G = gradMatrix(prob_v, prob_p)

A = stokesMatrix(K, G, prob_v, prob_p)
b = stokesRHS(f_u, prob_v, prob_p)

nu = prob_v.dim * prob_v.non
A[nu+1, :] .= 0
A[:, nu+1] .= 0
A[nu+1, nu+1] = 1
b[nu+1] = 0

x = A \ b

u_sol = x[1:nu]
p_sol = x[nu+1:end]


6859-element Vector{Float64}:
  0.0
  1.0028443453333335e8
  9.820665980610171e7
  9.734965272795291e7
  9.667829589151052e7
  9.991176701662366e7
  9.831416425005932e7
  1.007704658655845e8
  9.90253289844286e7
  9.748916694734861e7
  9.866266503267975e7
  9.484872364804725e7
  9.210007788699652e7
  ⋮
 -1.337878182526222e7
  2.4214443803373106e7
 -1.3760037566911029e7
  2.4580364355373707e7
 -1.3122326973632362e7
  2.4608903810456987e7
 -1.2813823785756884e7
  2.459938230674326e7
 -1.2668961337490488e7
  2.438835243580928e7
 -1.2620240876077978e7
 -1.2117666330128286e7