In [1]:
using LowLevelFEM
import LowLevelFEM as FEM

gmsh.initialize()

In [2]:
using SparseArrays, LinearAlgebra

In [3]:
gmsh.open("unit-cube.geo")

Info    : Reading 'unit-cube.geo'...
Info    : Meshing 1D...
Info    : [  0%] Meshing curve 1 (Line)
Info    : [ 10%] Meshing curve 2 (Line)
Info    : [ 20%] Meshing curve 3 (Line)
Info    : [ 30%] Meshing curve 4 (Line)
Info    : [ 40%] Meshing curve 5 (Line)
Info    : [ 50%] Meshing curve 6 (Line)
Info    : [ 60%] Meshing curve 7 (Line)
Info    : [ 60%] Meshing curve 8 (Line)
Info    : [ 70%] Meshing curve 9 (Line)
Info    : [ 80%] Meshing curve 10 (Line)
Info    : [ 90%] Meshing curve 11 (Line)
Info    : [100%] Meshing curve 12 (Line)
Info    : Done meshing 1D (Wall 0.000591301s, CPU 0.000571s)
Info    : Meshing 2D...
Info    : [  0%] Meshing surface 1 (Transfinite)
Info    : [ 20%] Meshing surface 2 (Transfinite)
Info    : [ 40%] Meshing surface 3 (Transfinite)
Info    : [ 60%] Meshing surface 4 (Transfinite)
Info    : [ 70%] Meshing surface 5 (Transfinite)
Info    : [ 90%] Meshing surface 6 (Transfinite)
Info    : Done meshing 2D (Wall 0.000161045s, CPU 0.000154s)
Info    : Meshin

In [4]:
hooke = FEM.material("body", E=260, ν=0.3)
nonlinear = FEM.material("body", E=260, ν=0.3, type=:StVenantKirchhoff)
nonlinear = FEM.material("body", E=260, ν=0.3, type=:NeoHookeCompressible)
lin = FEM.Problem([hooke])
nonlin = FEM.Problem([nonlinear])

Info    : RCMK renumbering...
Info    : Done RCMK renumbering (bandwidth is now 162)
Info    : RCMK renumbering...
Info    : Done RCMK renumbering (bandwidth is now 162)


LowLevelFEM.Problem("unit-cube", :Solid, 3, 3, LowLevelFEM.Material[LowLevelFEM.Material("body", :NeoHookeCompressible, 260.0, 0.3, 7.85e-9, 45.0, 4.2e8, 1.2e-5, 150.0, 100.0, 216.66666666666666)], 1.0, 245)

In [5]:
ux(x, y, z) = 0.5 * y * y
uy(x, y, z) = 0
uz(x, y, z) = 0

uz (generic function with 1 method)

In [6]:
disp = FEM.field("body", fx=ux, fy=uy, fz=uz)
u = FEM.vectorField(lin, [disp])

LowLevelFEM.VectorField(Matrix{Float64}[], [0.0; 0.0; … ; 0.0; 0.0;;], [0.0], Int64[], 1, :u3D)

In [7]:
FEM.showDoFResults(lin, u, :vector)

1

In [8]:
A1 = FEM.solveStrain(lin, u)
F1 = FEM.solveStress(lin, u)

LowLevelFEM.TensorField([[-9.71445146547012e-15; 33.33333333333335; … ; 0.0; 0.0;;], [0.0; 33.33333333333334; … ; 0.0; 0.0;;], [-3.885780586188048e-14; 66.66666666666667; … ; 0.0; 0.0;;], [3.885780586188048e-14; 66.66666666666674; … ; 0.0; 0.0;;], [0.0; 99.99999999999991; … ; 0.0; 0.0;;], [0.0; 100.00000000000009; … ; 0.0; 8.326672684688674e-15;;], [0.0; 33.33333333333333; … ; 0.0; 0.0;;], [-9.71445146547012e-15; 33.33333333333333; … ; 0.0; 0.0;;], [3.885780586188048e-14; 66.66666666666663; … ; 0.0; 0.0;;], [-3.885780586188048e-14; 66.66666666666666; … ; 0.0; 0.0;;], [0.0; 100.0; … ; 0.0; 0.0;;], [0.0; 100.0; … ; 0.0; 0.0;;], [0.0; 33.33333333333333; … ; 0.0; 0.0;;], [0.0; 33.33333333333333; … ; 0.0; 0.0;;], [0.0; 66.66666666666663; … ; 0.0; 2.0816681711721685e-15;;], [0.0; 66.66666666666663; … ; 0.0; 0.0;;], [0.0; 100.0; … ; 0.0; 0.0;;], [0.0; 100.0; … ; 0.0; 0.0;;]], Matrix{Float64}(undef, 0, 0), [0.0], [83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100], 1, :s)

In [9]:
FEM.showElementResults(lin, A1, :ex)
FEM.showElementResults(lin, A1, :ey)
FEM.showElementResults(lin, A1, :ez)
FEM.showElementResults(lin, A1, :exy)
FEM.showElementResults(lin, A1, :eyz)
FEM.showElementResults(lin, A1, :ezx)

Info    : Running Plugin(Smooth)...
Info    : Done running Plugin(Smooth)
Info    : Running Plugin(Smooth)...
Info    : Done running Plugin(Smooth)
Info    : Running Plugin(Smooth)...
Info    : Done running Plugin(Smooth)
Info    : Running Plugin(Smooth)...
Info    : Done running Plugin(Smooth)
Info    : Running Plugin(Smooth)...
Info    : Done running Plugin(Smooth)
Info    : Running Plugin(Smooth)...
Info    : Done running Plugin(Smooth)


7

In [10]:
#r1 = FEM.showDeformationResults(nonlinelast, r, :uvec)

In [11]:
FEM.probe(A1, 0.5, 0.5, 0.5)

3×3 Matrix{Float64}:
  4.18234e-47  0.25  -7.31853e-32
  0.25         0.0    0.0
 -7.31853e-32  0.0    0.0

In [12]:
R = FEM.nodePositionVector(lin)

LowLevelFEM.VectorField(Matrix{Float64}[], [0.0; 0.0; … ; 0.8333333333333331; 0.8333333333333337;;], [0.0], Int64[], 1, :u3D)

In [13]:
reshape(R.a, 3, :)

3×245 Matrix{Float64}:
 0.0  0.0  0.0  0.0  2.0  2.0  2.0  2.0  …  1.0       0.5       1.5
 0.0  0.0  1.0  1.0  0.0  0.0  1.0  1.0     0.833333  0.833333  0.833333
 1.0  0.0  1.0  0.0  1.0  0.0  1.0  0.0     0.833333  0.833333  0.833333

In [14]:
reshape(u.a, 3, :)

3×245 Matrix{Float64}:
 0.0  0.0  0.5  0.5  0.0  0.0  0.5  …  0.125  0.347222  0.347222  0.347222
 0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0    0.0       0.0       0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0    0.0       0.0       0.0

In [15]:
r = R + u

LowLevelFEM.VectorField(Matrix{Float64}[], [0.0; 0.0; … ; 0.8333333333333331; 0.8333333333333337;;], [0.0], Int64[], 1, :u3D)

In [16]:
problem = lin

dim = problem.dim
pdim = problem.pdim
nsteps = r.nsteps
numElem = []
v = []

for ipg in 1:length(problem.material)
    phName = problem.material[ipg].phName
    dim = problem.dim
    pdim = problem.pdim
    if problem.dim != 3 || problem.type != :Solid
        error("deformationGradient: dimension is $(problem.dim), problem type is $(problem.type). (They must be 3 and :Solid.)")
    end

    dimTags = gmsh.model.getEntitiesForPhysicalName(phName)
    for idm in 1:length(dimTags)
        dimTag = dimTags[idm]
        edim = dimTag[1]
        etag = dimTag[2]
        elemTypes, elemTags, elemNodeTags = gmsh.model.mesh.getElements(edim, etag)
        for i in 1:length(elemTypes)
            et = elemTypes[i]
            elementName, dim, order, numNodes::Int64, localNodeCoord, numPrimaryNodes = gmsh.model.mesh.getElementProperties(et)
            comp, dfun, ori = gmsh.model.mesh.getBasisFunctions(et, localNodeCoord, "Lagrange")
            #display("localNodeCoord:")
            #display(reshape(localNodeCoord, 3, :))
            v1 = zeros(3numNodes, nsteps)
            h = reshape(dfun, :, numNodes)
            H = spzeros(3 * numNodes, 3 * numNodes)
            sizehint!(H, 3 * numNodes * numNodes)
            for k in 1:numNodes, l in 1:numNodes
                for kk in 1:3
                    #H[k*3-(3-kk), l*3-(3-kk)] = h[(k-1)*numNodes+l]
                    H[k*3-(3-kk), l*3-(3-kk)] = h[k, l]
                end
            end
            nnet = zeros(Int, length(elemTags[i]), numNodes)
            nn2 = zeros(Int, pdim * numNodes)
            for j in 1:length(elemTags[i])
                elem = elemTags[i][j]
                for k in 1:numNodes
                    nnet[j, k] = elemNodeTags[i][(j-1)*numNodes+k]
                end
                #display("nnet: $(nnet[j,:])")
                for k in 1:pdim
                    nn2[k:pdim:pdim*numNodes] = pdim * nnet[j, :] .- (pdim - k)
                end
                #display("nn2: $(nn2')")
                push!(numElem, elem)
                for k in 1:numNodes
                    H1 = H[3k-(3-1):3k, 1:pdim*numNodes]
                    for kk in 1:nsteps
                        v0 = H1 * r.a[nn2, kk]
                        #display("v0 = $v0")
                        v1[3k-(3-1):3k, kk] .= [v0[1]; v0[2]; v0[3]]
                        #v1[3k-(3-1):3k, kk] = [k, v0[2], v0[3]]
                    end
                end
                #display(reshape(v1, 3, :))
                push!(v, v1)
            end
        end
    end
end
ret = FEM.VectorField(v, [;;], r.t, numElem, nsteps, :q3D)


LowLevelFEM.VectorField([[1.5; 1.0; … ; 0.8333333333333331; 0.8333333333333337;;], [1.5; 1.0; … ; 0.8333333333333331; 0.8333333333333337;;], [1.5; 1.0; … ; 0.8333333333333331; 0.8333333333333337;;], [1.5; 1.0; … ; 0.8333333333333331; 0.8333333333333337;;], [1.5; 1.0; … ; 0.8333333333333331; 0.8333333333333337;;], [1.5; 1.0; … ; 0.8333333333333331; 0.8333333333333337;;], [1.5; 1.0; … ; 0.8333333333333331; 0.8333333333333337;;], [1.5; 1.0; … ; 0.8333333333333331; 0.8333333333333337;;], [1.5; 1.0; … ; 0.8333333333333331; 0.8333333333333337;;], [1.5; 1.0; … ; 0.8333333333333331; 0.8333333333333337;;], [1.5; 1.0; … ; 0.8333333333333331; 0.8333333333333337;;], [1.5; 1.0; … ; 0.8333333333333331; 0.8333333333333337;;], [1.5; 1.0; … ; 0.8333333333333331; 0.8333333333333337;;], [1.5; 1.0; … ; 0.8333333333333331; 0.8333333333333337;;], [1.5; 1.0; … ; 0.8333333333333331; 0.8333333333333337;;], [1.5; 1.0; … ; 0.8333333333333331; 0.8333333333333337;;], [1.5; 1.0; … ; 0.8333333333333331; 0.8333333333

In [17]:
q = u
DoFResults = false

    nsteps = q.nsteps
    ε = []
    numElem = Int[]
    ncoord2 = zeros(3 * problem.non)
    dim = problem.dim
    pdim = problem.pdim
    non = problem.non
    type = :e
    if DoFResults == true
        E1 = zeros(non * 9, nsteps)
        pcs = zeros(Int64, non * dim)
    end

    for ipg in 1:length(problem.material)
        phName = problem.material[ipg].phName
        ν = problem.material[ipg].ν
        dim = 0
        if problem.dim == 3 && problem.type == :Solid
            dim = 3
            rowsOfB = 9
            b = 1
        elseif problem.dim == 2 && problem.type == :PlaneStress
            dim = 2
            rowsOfB = 3
            b = problem.thickness
        elseif problem.dim == 2 && problem.type == :PlaneStrain
            dim = 2
            rowsOfB = 3
            b = 1
        elseif problem.dim == 2 && problem.type == :AxiSymmetric
            dim = 2
            rowsOfB = 4
            b = 1
        else
            error("solveStrain: dimension is $(problem.dim), problem type is $(problem.type).")
        end

        dimTags = gmsh.model.getEntitiesForPhysicalName(phName)
        for idm in 1:length(dimTags)
            dimTag = dimTags[idm]
            edim = dimTag[1]
            etag = dimTag[2]
            elemTypes, elemTags, elemNodeTags = gmsh.model.mesh.getElements(edim, etag)
            nodeTags, ncoord, parametricCoord = gmsh.model.mesh.getNodes(dim, -1, true, false)
            ncoord2[nodeTags*3 .- 2] = ncoord[1:3:length(ncoord)]
            ncoord2[nodeTags*3 .- 1] = ncoord[2:3:length(ncoord)]
            ncoord2[nodeTags*3 .- 0] = ncoord[3:3:length(ncoord)]
            for i in 1:length(elemTypes)
                et = elemTypes[i]
                elementName, dim, order, numNodes::Int64, localNodeCoord, numPrimaryNodes = gmsh.model.mesh.getElementProperties(et)
                #e0 = zeros(rowsOfB * numNodes)
                nodeCoord = zeros(numNodes * 3)
                for k in 1:dim, j = 1:numNodes
                    nodeCoord[k+(j-1)*3] = localNodeCoord[k+(j-1)*dim]
                end
                comp, dfun, ori = gmsh.model.mesh.getBasisFunctions(et, nodeCoord, "GradLagrange")
                ∇h = reshape(dfun, :, numNodes)
                comp, fun, ori = gmsh.model.mesh.getBasisFunctions(et, nodeCoord, "Lagrange")
                h = reshape(fun, :, numNodes)
                nnet = zeros(Int, length(elemTags[i]), numNodes)
                invJac = zeros(3, 3numNodes)
                ∂h = zeros(3, numNodes * numNodes)
                B = zeros(rowsOfB * numNodes, pdim * numNodes)
                nn2 = zeros(Int, pdim * numNodes)
                r = zeros(numNodes)
                for j in 1:length(elemTags[i])
                    elem = elemTags[i][j]
                    for k in 1:numNodes
                        nnet[j, k] = elemNodeTags[i][(j-1)*numNodes+k]
                    end
                    jac, jacDet, coord = gmsh.model.mesh.getJacobian(elem, nodeCoord)
                    Jac = reshape(jac, 3, :)
                    for k in 1:numNodes
                        invJac[1:3, 3*k-2:3*k] = inv(Jac[1:3, 3*k-2:3*k])'
                        r[k] = h[:, k]' * ncoord2[nnet[j, :] * 3 .- 2]
                    end
                    ∂h .*= 0
                    for k in 1:numNodes, l in 1:numNodes
                        ∂h[1:dim, (k-1)*numNodes+l] = invJac[1:dim, k*3-2:k*3-(3-dim)] * ∇h[l*3-2:l*3-(3-dim), k] #??????????????????
                    end
                    B .*= 0
                    if dim == 2 && rowsOfB == 3
                        for k in 1:numNodes, l in 1:numNodes
                            B[k*3-0, l*2-0] = B[k*3-2, l*2-1] = ∂h[1, (k-1)*numNodes+l]
                            B[k*3-0, l*2-1] = B[k*3-1, l*2-0] = ∂h[2, (k-1)*numNodes+l]
                        end
                    elseif dim == 3 && rowsOfB == 9
                        for k in 1:numNodes, l in 1:numNodes
                            B[k*9-(9-1), l*3-(3-1)] = B[k*9-(9-2), l*3-(3-2)] = B[k*9-(9-3), l*3-(3-3)] = ∂h[1, (k-1)*numNodes+l]
                            B[k*9-(9-4), l*3-(3-1)] = B[k*9-(9-5), l*3-(3-2)] = B[k*9-(9-6), l*3-(3-3)] = ∂h[2, (k-1)*numNodes+l]
                            B[k*9-(9-7), l*3-(3-1)] = B[k*9-(9-8), l*3-(3-2)] = B[k*9-(9-9), l*3-(3-3)] = ∂h[3, (k-1)*numNodes+l]
                        end
                    elseif dim == 2 && rowsOfB == 4
                        for k in 1:numNodes, l in 1:numNodes
                            B[k*4-3, l*2-1] = B[k*4-0, l*2-0] = ∂h[1, (k-1)*numNodes+l]
                            B[k*4-1, l*2-0] = B[k*4-0, l*2-1] = ∂h[2, (k-1)*numNodes+l]
                            B[k*4-2, l*2-1] = r[k] < 1e-10 ? 0 : h[l, k] / r[k]
                        end
                    else
                        error("solveStrain: rows of B is $rowsOfB, dimension of the problem is $dim.")
                    end
                    push!(numElem, elem)
                    for k in 1:dim
                        nn2[k:dim:dim*numNodes] = dim * nnet[j, 1:numNodes] .- (dim - k)
                    end
                    e = zeros(9numNodes, nsteps) # tensors have nine elements
                    for k in 1:numNodes
                        if rowsOfB == 9 && dim == 3 && problem.type == :Solid
                            B1 = B[k*9-8:k*9, 1:3*numNodes]
                            for kk in 1:nsteps
                                e0 = B1 * q.a[nn2, kk]
                                if DoFResults == false
                                    e[(k-1)*9+1:k*9, kk] = [e0[1], e0[2], e0[3],
                                        e0[4], e0[5], e0[6],
                                        e0[7], e0[8], e0[9]]
                                end
                                if DoFResults == true
                                    E1[9*nnet[j, k]-8:9*nnet[j,k], kk] .+= [e0[1], e0[2], e0[3], e0[4], e0[5], e0[6], e0[7], e0[8], e0[9]]
                                end
                            end
                        elseif rowsOfB == 3 && dim == 2 && problem.type == :PlaneStress
                            B1 = B[k*3-2:k*3, 1:2*numNodes]
                            for kk in 1:nsteps
                                e0 = B1 * q.a[nn2, kk]
                                if DoFResults == false
                                    e[(k-1)*9+1:k*9, kk] = [e0[1], e0[3]/2, 0,
                                        e0[3]/2, e0[2], 0,
                                        0, 0, ν/(ν-1)*(e0[1]+e0[2])]
                                end
                                if DoFResults == true
                                    E1[9*nnet[j, k]-8:9*nnet[j,k], kk] .+= [e0[1], e0[3], 0, e0[3], e0[2], 0, 0, 0, ν/(ν-1)*(e0[1]+e0[2])]
                                end
                            end
                        elseif rowsOfB == 3 && dim == 2 && problem.type == :PlaneStrain
                            B1 = B[k*3-2:k*3, 1:2*numNodes]
                            for kk in 1:nsteps
                                e0 = B1 * q.a[nn2, kk]
                                if DoFResults == false
                                    e[(k-1)*9+1:k*9, kk] = [e0[1], e0[3]/2, 0,
                                        e0[3]/2, e0[2], 0,
                                        0, 0, 0]
                                end
                                if DoFResults == true
                                    E1[9*nnet[j, k]-8:9*nnet[j,k], kk] .+= [e0[1], e0[3], 0, e0[3], e0[2], 0, 0, 0, 0]
                                end
                            end
                        elseif rowsOfB == 4 && dim == 2 && problem.type == :AxiSymmetric
                            B1 = B[k*4-3:k*4, 1:2*numNodes]
                            for kk in 1:nsteps
                                e0 = B1 * q.a[nn2, kk]
                                if DoFResults == false
                                    e[(k-1)*9+1:k*9, kk] = [e0[1], e0[4]/2, 0,
                                        e0[4]/2, e0[3], 0,
                                        0, 0, e0[2]]
                                end
                                if DoFResults == true
                                    E1[9*nnet[j, k]-8:9*nnet[j,k], kk] .+= [e0[1], e0[4], 0, e0[4], e0[3], 0, 0, 0, e0[2]]
                                end
                            end
                        else
                            error("solveStrain: rowsOfB is $rowsOfB, dimension of the problem is $dim, problem type is $(problem.type).")
                        end
                    end
                    if DoFResults == true
                        pcs[nnet[j,1:numNodes]] .+= 1
                    end
                    if DoFResults == false
                        push!(ε, e)
                    end
                end
            end
        end
    end
    if DoFResults == true
        for k in 1:9
            for l in 1:non
                E1[k + 9 * l - 9, :] ./= pcs[l]
            end
        end
    end
    if DoFResults == true
        epsilon = FEM.TensorField([], E1, q.t, [], nsteps, type)
        #return epsilon
    else
        epsilon = FEM.TensorField(ε, [;;], q.t, numElem, nsteps, type)
        #return epsilon
    end




LowLevelFEM.TensorField([[-2.7755575615628914e-17; 0.0; … ; 0.0; 0.0;;], [0.0; 0.0; … ; 0.0; 0.0;;], [-1.1102230246251565e-16; 0.0; … ; 0.0; 0.0;;], [1.1102230246251565e-16; 0.0; … ; 0.0; 0.0;;], [0.0; 0.0; … ; 0.0; 0.0;;], [0.0; 0.0; … ; 0.0; 0.0;;], [0.0; 0.0; … ; 0.0; 0.0;;], [-2.7755575615628914e-17; 0.0; … ; 0.0; 0.0;;], [1.1102230246251565e-16; 0.0; … ; 0.0; 0.0;;], [-1.1102230246251565e-16; 0.0; … ; 0.0; 0.0;;], [0.0; 0.0; … ; 0.0; 0.0;;], [0.0; 0.0; … ; 0.0; 0.0;;], [0.0; 0.0; … ; 0.0; 0.0;;], [0.0; 0.0; … ; 0.0; 0.0;;], [0.0; 0.0; … ; 0.0; 0.0;;], [0.0; 0.0; … ; 0.0; 0.0;;], [0.0; 0.0; … ; 0.0; 0.0;;], [0.0; 0.0; … ; 0.0; 0.0;;]], Matrix{Float64}(undef, 0, 0), [0.0], [83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100], 1, :e)

In [18]:
FEM.probe(epsilon, 0.5, 0.5, 0.5)

3×3 Matrix{Float64}:
 4.18234e-47  0.5  -1.46371e-31
 0.0          0.0   0.0
 0.0          0.0   0.0

In [19]:
ret3 = FEM.showElementResults(problem, epsilon, :exy, name="new")

Info    : Running Plugin(Smooth)...
Info    : Done running Plugin(Smooth)


8

In [20]:
ret2 = FEM.elementsToNodes(problem, ret)

LowLevelFEM.VectorField(Matrix{Float64}[], [1.2222222222222223; 0.6666666666666666; … ; 0.8333333333333331; 0.8333333333333337;;], [0.0], Int64[], 1, :q3D)

In [21]:
FEM.showDeformationResults(problem, ret2, :qvec, name="test")

9

In [22]:
FEM.showDeformationResults(problem, ret2, :vector, name="elementsToNodes")

10

In [23]:
FEM.showDeformationResults(problem, r, :vector, name="r-orig")

ErrorException: type Array has no field a

In [24]:
D = FEM.deformationGradient(lin, u)

UndefVarError: UndefVarError: `q` not defined in `LowLevelFEM`
Suggestion: check for spelling errors or missing imports.

In [25]:
gmsh.model.mesh.getLocalCoordinatesInElement(27, 0, 0, 0)

(-1.0, -19.0, 38.0)

In [26]:
FEM.probe(D, 0.5, 0.5, 0.5)

UndefVarError: UndefVarError: `D` not defined in `Main`
Suggestion: check for spelling errors or missing imports.

In [27]:
D = epsilon
A2 = (D + D') / 2

LowLevelFEM.TensorField([[-2.7755575615628914e-17; 0.16666666666666674; … ; 0.0; 0.0;;], [0.0; 0.1666666666666667; … ; 0.0; 0.0;;], [-1.1102230246251565e-16; 0.33333333333333337; … ; 0.0; 0.0;;], [1.1102230246251565e-16; 0.3333333333333337; … ; 0.0; 0.0;;], [0.0; 0.49999999999999956; … ; 0.0; 0.0;;], [0.0; 0.5000000000000004; … ; 0.0; 0.0;;], [0.0; 0.16666666666666663; … ; 0.0; 0.0;;], [-2.7755575615628914e-17; 0.16666666666666663; … ; 0.0; 0.0;;], [1.1102230246251565e-16; 0.33333333333333315; … ; 0.0; 0.0;;], [-1.1102230246251565e-16; 0.33333333333333326; … ; 0.0; 0.0;;], [0.0; 0.5; … ; 0.0; 0.0;;], [0.0; 0.5; … ; 0.0; 0.0;;], [0.0; 0.16666666666666663; … ; 0.0; 0.0;;], [0.0; 0.16666666666666663; … ; 0.0; 0.0;;], [0.0; 0.33333333333333315; … ; 0.0; 0.0;;], [0.0; 0.33333333333333315; … ; 0.0; 0.0;;], [0.0; 0.5; … ; 0.0; 0.0;;], [0.0; 0.5; … ; 0.0; 0.0;;]], Matrix{Float64}(undef, 0, 0), [0.0], [83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100], 1, :e)

In [28]:
FEM.probe(A1, 0.5, 0.5, 0.5)


3×3 Matrix{Float64}:
  4.18234e-47  0.25  -7.31853e-32
  0.25         0.0    0.0
 -7.31853e-32  0.0    0.0

In [29]:
FEM.probe(A2, 0.5, 0.5, 0.5)

3×3 Matrix{Float64}:
  4.18234e-47  0.25  -7.31853e-32
  0.25         0.0    0.0
 -7.31853e-32  0.0    0.0

In [30]:
A3 = FEM.elementsToNodes(problem, A2)

LowLevelFEM.TensorField(Matrix{Float64}[], [0.0; 0.0; … ; 0.0; 0.0;;], [0.0], Int64[], 1, :e)

In [31]:
FEM.probe(A3, 0.5, 0.5, 0.5)

3×3 Matrix{Float64}:
  4.62223e-33  0.25  -3.62075e-32
  0.25         0.0    0.0
 -3.62075e-32  0.0    0.0

In [32]:
Ex = lin.material[1].E
ν = lin.material[1].ν
I = unitTensor(A2)
F2 = Ex / (1 + ν) * (A2 + ν / (1 - 2ν) * I * trace(A2))

LowLevelFEM.TensorField([[-5.551115123125783e-15; 33.33333333333335; … ; 0.0; 0.0;;], [0.0; 33.33333333333334; … ; 0.0; 0.0;;], [-2.220446049250313e-14; 66.66666666666667; … ; 0.0; 0.0;;], [2.220446049250313e-14; 66.66666666666674; … ; 0.0; 0.0;;], [0.0; 99.99999999999991; … ; 0.0; 0.0;;], [0.0; 100.00000000000009; … ; 0.0; 0.0;;], [0.0; 33.33333333333333; … ; 0.0; 0.0;;], [-5.551115123125783e-15; 33.33333333333333; … ; 0.0; 0.0;;], [2.220446049250313e-14; 66.66666666666663; … ; 0.0; 0.0;;], [-2.220446049250313e-14; 66.66666666666666; … ; 0.0; 0.0;;], [0.0; 100.0; … ; 0.0; 0.0;;], [0.0; 100.0; … ; 0.0; 0.0;;], [0.0; 33.33333333333333; … ; 0.0; 0.0;;], [0.0; 33.33333333333333; … ; 0.0; 0.0;;], [0.0; 66.66666666666663; … ; 0.0; 0.0;;], [0.0; 66.66666666666663; … ; 0.0; 0.0;;], [0.0; 100.0; … ; 0.0; 0.0;;], [0.0; 100.0; … ; 0.0; 0.0;;]], Matrix{Float64}(undef, 0, 0), [0.0], [83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100], 1, :e)

In [33]:
FEM.probe(F2, 0.5, 0.5, 0.5)

3×3 Matrix{Float64}:
 -2.31112e-31  50.0          -1.46371e-29
 50.0          -2.31112e-31   0.0
 -1.46371e-29   0.0          -2.31112e-31

In [34]:
FEM.showElementResults(lin, A2, :ex)
FEM.showElementResults(lin, A2, :ey)
FEM.showElementResults(lin, A2, :ez)
FEM.showElementResults(lin, A2, :exy)
FEM.showElementResults(lin, A2, :eyz)
FEM.showElementResults(lin, A2, :ezx)

Info    : Running Plugin(Smooth)...
Info    : Done running Plugin(Smooth)
Info    : Running Plugin(Smooth)...
Info    : Done running Plugin(Smooth)
Info    : Running Plugin(Smooth)...
Info    : Done running Plugin(Smooth)
Info    : Running Plugin(Smooth)...
Info    : Done running Plugin(Smooth)
Info    : Running Plugin(Smooth)...
Info    : Done running Plugin(Smooth)
Info    : Running Plugin(Smooth)...
Info    : Done running Plugin(Smooth)


16

In [35]:
FEM.openPostProcessor()

-------------------------------------------------------
Version       : 4.13.1
License       : GNU General Public License
Build OS      : Linux64-sdk
Build date    : 19700101
Build host    : amdci7.julia.csail.mit.edu
Build options : 64Bit ALGLIB[contrib] ANN[contrib] Bamg Blossom Cairo DIntegration Dlopen DomHex Eigen[contrib] Fltk GMP Gmm[contrib] Hxt Jpeg Kbipack LinuxJoystick MathEx[contrib] Mesh Metis[contrib] Mmg Mpeg Netgen Nii2mesh ONELAB ONELABMetamodel OpenCASCADE OpenCASCADE-CAF OpenGL OpenMP OptHom Parser Plugins Png Post QuadMeshingTools QuadTri Solver TetGen/BR TinyXML2[contrib] Untangle Voro++[contrib] WinslowUntangler Zlib
FLTK version  : 1.3.8
OCC version   : 7.7.2
Packaged by   : root
Web site      : https://gmsh.info
Issue tracker : https://gitlab.onelab.info/gmsh/gmsh/issues
-------------------------------------------------------


XOpenIM() failed
XRequest.18: BadValue 0x0


In [36]:
gmsh.finalize()