In [170]:
using LowLevelFEM
import LowLevelFEM as FEM

gmsh.initialize()

In [171]:
gmsh.open("DINAMIC_BIG.geo")

Info    : Reading 'DINAMIC_BIG.geo'...
Info    : Meshing 1D...
Info    : [  0%] Meshing curve 1 (Line)
Info    : [ 10%] Meshing curve 2 (Line)
Info    : [ 10%] Meshing curve 3 (Line)
Info    : [ 10%] Meshing curve 4 (Line)
Info    : [ 10%] Meshing curve 5 (Circle)
Info    : [ 20%] Meshing curve 6 (Circle)
Info    : [ 20%] Meshing curve 7 (Circle)
Info    : [ 20%] Meshing curve 8 (Circle)
Info    : [ 20%] Meshing curve 9 (Circle)
Info    : [ 20%] Meshing curve 10 (Circle)
Info    : [ 30%] Meshing curve 11 (Circle)
Info    : [ 30%] Meshing curve 12 (Circle)
Info    : [ 30%] Meshing curve 13 (Circle)
Info    : [ 30%] Meshing curve 14 (Circle)
Info    : [ 30%] Meshing curve 15 (Circle)
Info    : [ 40%] Meshing curve 16 (Circle)
Info    : [ 40%] Meshing curve 17 (Circle)
Info    : [ 40%] Meshing curve 18 (Circle)
Info    : [ 40%] Meshing curve 19 (Circle)
Info    : [ 40%] Meshing curve 20 (Circle)
Info    : [ 50%] Meshing curve 21 (Circle)
Info    : [ 50%] Meshing curve 22 (Circle)
Info    

In [172]:
alu = FEM.material("alu", E=0.71e5, ν=0.334, ρ=2.7e-9)
vas = FEM.material("vas", E=1.96e5, ν=0.25, ρ=7.87e-9)
problem = FEM.Problem([alu, vas], type=:PlaneStress)

Info    : RCMK renumbering...
Info    : Done RCMK renumbering (bandwidth is now 216)


LowLevelFEM.Problem("DINAMIC_BIG", :PlaneStress, 2, 2, LowLevelFEM.Material[LowLevelFEM.Material("alu", 71000.0, 0.334, 2.7e-9, 45.0, 4.2e8, 1.2e-5), LowLevelFEM.Material("vas", 196000.0, 0.25, 7.87e-9, 45.0, 4.2e8, 1.2e-5)], 1.0, 15900)

In [173]:
supp = FEM.displacementConstraint("left", ux=0, uy=0)
force = FEM.load("right", fx=-1)
f = FEM.loadVector(problem, [force])

31800-element Vector{Float64}:
  0.0
  0.0
  0.0
  0.0
 -0.012499999999999956
  0.0
 -0.012499999999999956
  0.0
  0.0
  0.0
  ⋮
  0.0
  0.0
  0.0
  0.0
  0.0
  0.0
  0.0
  0.0
  0.0

In [174]:
K = FEM.stiffnessMatrix(problem)

31800×31800 SparseArrays.SparseMatrixCSC{Float64, Int64} with 459102 stored entries:
⎡⡿⣯⡉⠉⠉⠉⠉⠉⠉⠉⠉⢹⣿⣿⡍⠻⣑⢐⠟⡿⡗⡶⣶⣿⣿⣷⣿⣿⣿⣿⢿⣯⠉⠉⠉⠉⠩⠀⠤⠭⎤
⎢⡇⠈⠻⣦⡀⠀⠀⠀⠀⠀⠀⢸⣿⣿⠀⠠⠘⠀⡃⢸⠷⣿⣿⣿⣷⣷⣭⢿⣿⣼⣻⡟⣧⠀⠀⠀⠀⠀⠀⠀⎥
⎢⡇⠀⠀⠈⠻⣦⡀⠀⠀⠀⠀⢸⣿⣿⣆⡠⠨⠰⢫⣞⡧⠢⢾⣿⣗⣷⢿⢮⠞⣿⣸⡇⠘⣧⠀⠀⠀⠀⠀⠀⎥
⎢⡇⠀⠀⠀⠀⠈⠻⣦⡀⠀⠀⢸⣿⣿⠂⠀⠀⠀⠃⠚⠆⠀⠘⢿⣿⣟⢿⡟⣿⣧⠉⠁⠀⠘⣧⠀⠀⠀⠀⠀⎥
⎢⡇⠀⠀⠀⠀⠀⠀⠈⠻⣦⡀⢸⣿⣿⡣⣅⣿⣠⣟⣿⡷⣝⣿⣿⣻⣿⣾⣽⣿⣷⣿⡇⠀⠀⠘⣧⠀⠀⠀⠀⎥
⎢⣇⣀⣀⣀⣀⣀⣀⣀⣀⣈⣻⣾⠿⠿⢐⣠⣀⣠⣂⣯⣌⣀⣐⣭⣿⣷⣿⣿⣯⣫⣝⡃⠀⠀⠀⠘⣧⢀⣀⣀⎥
⎢⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⠱⣦⣾⣻⣿⣹⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⣧⡉⠀⡀⠈⡹⠈⠀⠍⢮⠐⣰⣾⣻⡻⣮⡽⢈⢽⣿⣷⡮⡿⣿⣿⣿⣿⣿⣿⣿⣿⡇⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⢑⢘⠒⠀⢂⡂⠀⠀⠛⣻⠀⣸⣟⣻⡓⢋⣻⣾⣿⣿⣿⣲⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⣿⡥⣉⣈⣫⢶⣩⠀⣿⣽⡬⣼⣿⣿⣷⣷⣿⣿⣿⣿⣿⣯⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⢹⡭⣽⣧⠩⡋⠈⠁⣝⢯⠂⢹⣿⣿⡹⡿⢻⣻⡿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⣼⣿⣿⣿⣾⣷⣶⣄⣿⣿⡔⣼⣿⣿⣿⣯⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⢿⣿⢽⣿⢽⣽⣿⢿⣿⣾⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⣿⣿⣧⣟⡻⣗⣿⠷⣞⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⣿⣿⣛⣿⣾⣥⠿⣿⢿⣿⡯⣻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⡿⣷⣿⠾⠶⠾⠇⠀⠿⠿⠷⠹⠿⠿⠿⠿⠿⠿⠿⠿⠿⠿⠿⠿⠿⠿⠿⠿⠿⠿⠿⣧⡀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⡇⠀⠉⠛⠶⣤⣀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠻⣦⡀⠀⠀⠀⠀⠀⎥
⎢⡇⠀⠀⠀⠀⠀⠉⠛⠶⣤⣀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠻⣦⡀⠀⠀⠀⎥
⎢⠃⠂⠀⠀⠀⠀⠀⠀⠀⠀⠉⢛⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⢻⣶⣶⣶⎥
⎣⡄⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⣿⣿⎦

In [175]:
M = FEM.massMatrix(problem)

31800×31800 SparseArrays.SparseMatrixCSC{Float64, Int64} with 31800 stored entries:
⎡⠑⢄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎤
⎢⠀⠀⠑⢄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠑⢄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠑⢄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠑⢄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠑⢄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠑⢄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠑⢄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠑⢄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠑⢄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠑⢄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠑⢄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠑⢄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠑⢄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠑⢄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠑⢄⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠑⢄⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠑⢄⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠑⢄⠀⠀⎥
⎣⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠑⢄⎦

In [176]:
ωmax = 2π / FEM.smallestPeriodTime(K, M)

2.0321942607664769e9

In [177]:
C = FEM.dampingMatrix(K, M, ωmax, β=0)

31800×31800 SparseArrays.SparseMatrixCSC{Float64, Int64} with 0 stored entries:
⎡⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎤
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎣⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎦

In [178]:
u0 = FEM.initialDisplacement(problem, "alu", ux=0, uy=0)
v0 = FEM.initialVelocity(problem, "alu", vx=0, vy=0);

In [179]:
Δt = 2 / ωmax
u1, v1, t1 = FEM.CDM(K, M, C, f, u0, v0, 5Δt, Δt)

([0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0; … ; 0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0], [0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0; … ; 0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0], [0.0, 9.841578822517026e-10, 1.968315764503405e-9, 2.952473646755108e-9, 3.93663152900681e-9])

In [180]:
u2, v2, t2 = FEM.CDM(K, M, C, 0f, u1[:, size(u1, 2)], v1[:, size(v1, 2)], 500Δt, Δt)
t2 .+= last(t1) + Δt

500-element Vector{Float64}:
 4.920789411258513e-9
 5.904947293510215e-9
 6.8891051757619174e-9
 7.87326305801362e-9
 8.857420940265324e-9
 9.841578822517025e-9
 1.0825736704768727e-8
 1.180989458702043e-8
 1.2794052469272133e-8
 1.3778210351523837e-8
 ⋮
 4.881423095968485e-7
 4.891264674791002e-7
 4.90110625361352e-7
 4.910947832436037e-7
 4.920789411258554e-7
 4.930630990081071e-7
 4.940472568903588e-7
 4.950314147726106e-7
 4.960155726548623e-7

In [181]:
S1 = FEM.solveStress(problem, u1)

LowLevelFEM.TensorField([[0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0; … ; 0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0], [0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0; … ; 0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0], [0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0; … ; 0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0], [0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0; … ; 0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0], [0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0; … ; 0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0], [0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0; … ; 0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0], [0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0; … ; 0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0], [0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0; … ; 0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0], [0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0; … ; 0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0], [0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0; … ; 0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0]  …  [0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0; … ; 0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0], [0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0; … ; 0.0 0.0 … 0.0 0.0; 0.0 0.0 

In [182]:
S2 = FEM.solveStress(problem, u2)

LowLevelFEM.TensorField([[0.0 0.0 … -0.0009081328441039162 -0.0008627955955958283; 0.0 0.0 … 0.0005340517315430187 0.0005120409250869991; … ; 0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0], [0.0 0.0 … -0.044653471026229345 0.0066437053497960105; 0.0 0.0 … 0.02905976692467706 0.020156024681539365; … ; 0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0], [0.0 0.0 … 0.026955966540076905 0.035139125019781246; 0.0 0.0 … -0.04570972122559562 -0.03821633361196253; … ; 0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0], [0.0 0.0 … -0.00027188763928405425 -0.000293843724391153; 0.0 0.0 … 0.0006759912333531296 0.0006795512154477481; … ; 0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0], [0.0 0.0 … -0.023091971459205222 -0.026007989099801978; 0.0 0.0 … 0.000701192214590504 0.003200221520391721; … ; 0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0], [0.0 0.0 … 0.005691058203387982 0.009361640543245071; 0.0 0.0 … 0.006978800358190417 0.008180055933089092; … ; 0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0], [0.0 0.0 … -0.0005663044861586713 -0.0005876066818068065; 0.

In [183]:
S1 = FEM.elementsToNodes(problem, S1)

143100×5 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 ⋮                   
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

In [184]:
S2 = FEM.elementsToNodes(problem, S2)

143100×500 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  -0.00667343   -0.00686272
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0      0.000337094   0.000385708
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0      0.0           0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0      0.000337094   0.000385708
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0      0.000178186   0.000213464
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …   0.0           0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0      0.0           0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0      0.0           0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0      0.0           0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     -0.0093374    -0.00920843
 ⋮                        ⋮                   ⋱                
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     -0.000329063  -0.000372926
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     -8.25248e-5   -9.19754e-5
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0

In [185]:
sx1 = FEM.showDoFResults(problem, S1, :sx, t=t1)

-------------------------------------------------------
Version       : 4.13.1
License       : GNU General Public License
Build OS      : Linux64-sdk
Build date    : 19700101
Build host    : amdci7.julia.csail.mit.edu
Build options : 64Bit ALGLIB[contrib] ANN[contrib] Bamg Blossom Cairo DIntegration Dlopen DomHex Eigen[contrib] Fltk GMP Gmm[contrib] Hxt Jpeg Kbipack LinuxJoystick MathEx[contrib] Mesh Metis[contrib] Mmg Mpeg Netgen Nii2mesh ONELAB ONELABMetamodel OpenCASCADE OpenCASCADE-CAF OpenGL OpenMP OptHom Parser Plugins Png Post QuadMeshingTools QuadTri Solver TetGen/BR TinyXML2[contrib] Untangle Voro++[contrib] WinslowUntangler Zlib
FLTK version  : 1.3.8
OCC version   : 7.7.2
Packaged by   : root
Web site      : https://gmsh.info
Issue tracker : https://gitlab.onelab.info/gmsh/gmsh/issues
-------------------------------------------------------


0

In [ ]:
sx2 = FEM.showDoFResults(problem, S2, :sx, t=t2)

In [ ]:
nodes, steps = size(S2)
nodes ÷= 9
q = zeros(2 * nodes, steps)
for i in 1:steps
    for j in 1:nodes
        q[(j-1)*2+1, i] = S2[(j-1)*9+1, i] * v2[(j-1)*2+1, i] + S2[(j-1)*9+4, i] * v2[(j-1)*2+2, i]
        q[(j-1)*2+2, i] = S2[(j-1)*9+2, i] * v2[(j-1)*2+1, i] + S2[(j-1)*9+5, i] * v2[(j-1)*2+2, i]
    end
end
q .*= -1;

In [ ]:
q2 = FEM.showDoFResults(problem, q, :qvec, t=t2)

In [ ]:
gmsh.fltk.run()

In [ ]:
gmsh.finalize()

In [ ]:
size(S2)

In [ ]:
size(v2)